spring.datasource.url=jdbc:mysql://localhost:3306/campuscart_db
spring.datasource.username=root
spring.datasource.password=yogi@0964

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082